const cfg = window.SUPABASE_CONFIG;
const { createClient } = supabase;
const client = createClient(cfg.url, cfg.anonKey);
const $ = id => document.getElementById(id);

const loginView=$('loginView'),mfaView=$('mfaView'),appView=$('appView');
const type=$('type'),category=$('category');
const categories={project:[['general','General'],['cad','CAD'],['cfd','CFD'],['fea','FEA'],['ai','AI / ML'],['robotics','Robotics'],['manufacturing','Manufacturing'],['software','Software'],['iot','IoT / Automation']],research:[['research','Research'],['ai','AI / ML'],['cfd','CFD'],['materials','Materials'],['manufacturing','Manufacturing'],['robotics','Robotics']],publication:[['journal','Journal'],['conference','Conference'],['presentation','Presentation'],['poster','Poster'],['preprint','Preprint'],['manuscript','Manuscript']],certification:[['design','Design / CAD'],['simulation','Simulation'],['additive','Additive Manufacturing'],['engineering','Engineering'],['training','Training'],['membership','Membership'],['conference','Conference'],['ai','AI / ML'],['other','Other']],award:[['academic','Academic'],['competition','Competition'],['professional','Professional'],['other','Other']],media:[['image','Image'],['video','Video'],['3d','3D Model'],['figure','Figure'],['presentation','Presentation']],other:[['other','Other']]};
function updateCategory(){category.innerHTML=(categories[type.value]||categories.other).map(([v,l])=>`<option value="${v}">${l}</option>`).join('');}
function msg(el,text){el.textContent=text;}
async function requireMfaSession(){const {data:{session}}=await client.auth.getSession();if(!session)return false; if(session.user?.app_metadata?.role!=='admin')return false; return session;}

$('loginForm').addEventListener('submit',async e=>{e.preventDefault();msg($('loginMessage'),'Signing in…');const {data,error}=await client.auth.signInWithPassword({email:$('email').value,password:$('password').value});if(error){msg($('loginMessage'),error.message);return;}const aal=await client.auth.mfa.getAuthenticatorAssuranceLevel();if(aal.data?.currentLevel==='aal1'&&aal.data?.nextLevel==='aal2'){loginView.classList.add('hidden');mfaView.classList.remove('hidden');msg($('mfaMessage'),'');return;}await enterApp();});
$('mfaForm').addEventListener('submit',async e=>{e.preventDefault();msg($('mfaMessage'),'Verifying…');const factors=await client.auth.mfa.listFactors();const factor=factors.data?.totp?.find(x=>x.status==='verified');if(!factor){msg($('mfaMessage'),'No verified authenticator factor was found.');return;}const ch=await client.auth.mfa.challenge({factorId:factor.id});if(ch.error){msg($('mfaMessage'),ch.error.message);return;}const v=await client.auth.mfa.verify({factorId:factor.id,challengeId:ch.data.id,code:$('mfaCode').value.trim()});if(v.error){msg($('mfaMessage'),v.error.message);return;}await enterApp();});
async function enterApp(){const session=await requireMfaSession();if(!session){await client.auth.signOut();loginView.classList.remove('hidden');mfaView.classList.add('hidden');msg($('loginMessage'),'This account is not authorized as the portfolio admin.');return;}loginView.classList.add('hidden');mfaView.classList.add('hidden');appView.classList.remove('hidden');await load();}
$('logout').onclick=async()=>{await client.auth.signOut();location.reload();};
async function load(){const {data,error}=await client.from('content').select('*').order('created_at',{ascending:false});if(error){alert(error.message);return;}window.items=data||[];renderStats();renderList();}
function renderStats(){const types=['project','research','publication','certification','award','media'];$('stats').innerHTML=types.map(t=>`<div class="stat"><strong>${window.items.filter(x=>x.type===t).length}</strong><span>${t.toUpperCase()}</span></div>`).join('');}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function renderList(){const q=$('search').value.toLowerCase();const data=window.items.filter(x=>`${x.title} ${x.type} ${x.category}`.toLowerCase().includes(q));$('contentList').innerHTML=data.length?data.map(x=>`<article class="item"><div><span class="pill">${esc(x.type)}</span><span class="status ${x.published?'published':'draft'}"> · ${x.published?'PUBLISHED':'DRAFT'}</span><h4>${esc(x.title)}</h4><p>${esc(x.category||'')} · ${esc((x.technologies||[]).join(' · '))}</p></div><button class="danger" data-id="${x.id}">Delete</button></article>`).join(''):'<p class="empty">No content yet.</p>';document.querySelectorAll('.danger').forEach(b=>b.onclick=()=>removeItem(b.dataset.id));}
async function removeItem(id){if(!confirm('Delete this item?'))return;const {error}=await client.from('content').delete().eq('id',id);if(error){alert(error.message);return;}await load();}
$('search').addEventListener('input',renderList);
type.addEventListener('change',updateCategory);updateCategory();
$('contentForm').addEventListener('submit',async e=>{e.preventDefault();msg($('formMessage'),'Saving…');const {data:{user}}=await client.auth.getUser();if(!user){msg($('formMessage'),'Your session has expired.');return;}const slugBase=$('title').value.trim().toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');const slug=`${slugBase}-${crypto.randomUUID().slice(0,8)}`;const row={type:type.value,title:$('title').value.trim(),slug,category:category.value,description:$('description').value.trim(),technologies:$('technologies').value.split(',').map(s=>s.trim()).filter(Boolean),external_url:$('externalUrl').value.trim()||null,date:$('date').value||null,issuer:$('issuer').value.trim()||null,credential_id:$('credentialId').value.trim()||null,status:$('status').value.trim()||null,featured:$('featured').checked,published:$('published').checked,owner_id:user.id};const ins=await client.from('content').insert(row).select().single();if(ins.error){msg($('formMessage'),ins.error.message);return;}const files=$('files').files;for(const file of files){const path=`${user.id}/${ins.data.id}/${crypto.randomUUID()}-${file.name.replace(/[^a-zA-Z0-9._-]/g,'-')}`;const up=await client.storage.from('portfolio-public').upload(path,file,{upsert:false});if(up.error){msg($('formMessage'),`Saved item, but file upload failed: ${up.error.message}`);continue;}const meta={content_id:ins.data.id,bucket:'portfolio-public',storage_path:path,original_name:file.name,mime:file.type||null,size_bytes:file.size,owner_id:user.id};const m=await client.from('content_files').insert(meta);if(m.error)console.error(m.error);}msg($('formMessage'),'Saved.');e.target.reset();$('published').checked=true;updateCategory();await load();});
(async()=>{const {data:{session}}=await client.auth.getSession();if(session)await enterApp();})();
